name: BigBrother
version: 1.6.0-beta
api: [3.1.0, 4.0.0]
description: "Allows the connection of Minecraft: PC clients to PocketMine-MP servers"
author: BigBrotherTeam
website: https://github.com/BigBrotherTeam/BigBrother
load: STARTUP
main: shoghicp\BigBrother\BigBrother
